CREATE TABLE tts_voices (
    id   BIGINT GENERATED GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE mods (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      BIGINT NOT NULL,
    name         TEXT   NOT NULL,
    description  TEXT   NOT NULL,
    version      TEXT   NOT NULL,
    CONSTRAINT fk_game FOREIGN KEY (game_id) REFERENCES games(id)
);

CREATE TABLE alternatives (
    mod_id         BIGINT      NOT NULL,
    recording_id   BIGINT      NOT NULL,
    tts_voice_id   BIGINT      NOT NULL,
    transcript     TEXT        NOT NULL,
    state          VARCHAR(32) NOT NULL DEFAULT 'none',
    wave           TEXT,
    PRIMARY KEY (mod_id, recording_id),
    CONSTRAINT fk_mod FOREIGN KEY (mod_id) REFERENCES mods(id),
    CONSTRAINT fk_recording FOREIGN KEY (recording_id) REFERENCES recordings(id),
    CONSTRAINT fk_tts_voice FOREIGN KEY (tts_voice_id) REFERENCES tts_voices(id)
);
